### ISSUE TITLE
Deno起動後に他のデバイスからシステムにアクセスしたい

### ISSUE THREAD

**Issue by yuukia11** [fkpc/kanirobocon-system#2]
WindowsOSでDenoを手順通りに起動しました。
http://localhost:8000/で自身の端末からは閲覧できたのですが、
他の端末からブラウザでhttp://192.168.XXX.XXX:8000/とIPを指定して表示しても、
自身の端末のブラウザでIP指定して以下のメッセージが表示され、閲覧できませんでした。

”このサイトにアクセスできません
192.168.1.161 で接続が拒否されました。"

ポート開放やファイアウォール停止、ウイルス対策ソフトの停止を実施しましたが改善されませんでした。
Windows端末を管理サーバーとし、iPadなどのデバイスで入力をする想定でおりましたので、
他のデバイスからの参照、編集は必須と考えております。

不勉強で申し訳ないのですが、対処方法をお教えください。
よろしくお願いいたします。

**Comment by taisukef** [comment]
同一ネットワークで接続するか、接続できるように設定する必要があります
起動した端末のIPアドレスを起動したパソコンで見ることはできますか？

**Comment by yuukia11** [comment]
素早いご回答ありがとうございます！
はい、他のデバイスは同一ネットワーク内にいてPINGも問題なく飛びました。
Deno起動端末で設定した共有フォルダも見れているので、通信自体は問題なくできています。

Deno起動端末でIPアドレスを確認し、起動端末自身のブラウザのアドレスバーで、http://192.168.XXX.XXX:8000/ と入力してみたのですが、先程のメッセージが出ます。別の端末でDenoを起動しても同様の結果になりました。

Denoのバージョンは1.26.2です。
起動時にPowerShellで以下のテキストが表示されるのですが、何か関係がありますでしょうか？

Listening on http://[::]:8000/

**Comment by taisukef** [comment]
IPv6でサーバーを立てていたためIPv4環境で動かない可能性がありました
IPv4対応オプションを追加したので、下記コマンドで再度お試しください
```bash
deno run -A -r kanirobo-server.js --ipv4
```
-r オプションでライブラリを読み込み直します、次回からは下記でOKです
```bash
deno run -A kanirobo-server.js --ipv4
```

**Comment by yuukia11** [comment]
ご対応ありがとうございます！
今ほどテストしてみたのですが、このようなエラーメッセージが出てきました。
関数が無いようなメッセージですが、何か分かりますでしょうか？

`PS C:\kanirobocon-system-main> deno run -A -r kanirobo-server.js --ipv4 8888
error: Uncaught TypeError: Deno.consoleSize is not a function
    columns: Deno.consoleSize().columns,
                  ^
    at https://code4fukui.github.io/commander-es/lib/nodelike/process.js:5:19`

**Comment by taisukef** [comment]
deno upgrade と実行し、denoを最新版にしてください

**Comment by yuukia11** [comment]
ご指摘ありがとうございます！
アップグレードでエラーは出なくなったのですが、
やはり以前と同様に接続が拒否されてしまいました。。

IPv4では動かないということでしょうか。。
node.jsでHTTPサーバーを起動してテストしたところ、
遅いながらも外部からIPv4のアドレスで接続できたので、
端末のセキュリティ設定が影響しているとは考えにくいようにも感じます。
kanirobo-server.js内で何か環境に合わせた追記が必要でしたらお教えください。

IPv6で接続を試してみたところ、こちらは無事外部のパソコンから接続することができました。
しかし、iPadでIPv6のローカルIPアドレスが取得できず、同一のWi-Fi下にあっても参照することができませんでした。

大会をされる際はいつもどのようなデバイスで環境を作っておられますか？

**Comment by taisukef** [comment]
おかしいですね
表示は、 http://localhost:8888/ となっていたでしょうか？
Node.js でのHTTPサーバーと同じポートでも試してみていただけるでしょうか？

前回の大会では、VPSでサーバーを立ち上げて運用していました
https://web.arena.ne.jp/indigo/
こちらのVPSを使えば、1時間0.5円程度で借りられます

**Comment by yuukia11** [comment]
はい、実行結果はこのような表示が出ます。ポートをNode.jsと同じポートに変更しました↓↓

PS C:\kanirobocon-system-main> deno run -A -r kanirobo-server.js --ipv4 8080
Listening on http://localhost:8080/

Node.jsでhttp-serverを実行した結果はこちらです。下から２行目にあるように、IPアドレスが表示されて、外部からのアクセスもできました↓↓

PS C:\kanirobocon-system-main> http-server
Starting up http-server, serving ./

http-server version: 14.1.1

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://192.168.XXX.XXX:8080
  http://127.0.0.1:8080


VPSのご紹介ありがとうございます！
こちらで試してみようと思います！

**Comment by taisukef** [comment]
ご確認ありがとうございます

Windowsでのlocalhost/127.0.0.1ではだめだった可能性があります
立ち上げるhostnameを localhost ではなく 0.0.0.0 に変更してみました
https://github.com/code4fukui/wsutil

再度、-r オプションで起動お試しいただけるでしょうか？

**Comment by yuukia11** [comment]
ご対応ありがとうございます！
再度テストしてみたところ、IPv4にて他端末からの接続できるようになりました！

無事ログインもできたのですが、何点か以前と異なる動きをしていて、全体的にJSがうまく機能していないように感じました。

・エントリー受付の画面に遷移しても名簿のリストが表示されない（以前は表示されていました。一式を再ダウンロードしても同様の結果でした。）
・iPadでログインボタンが押せない（WindowsPCはOK）。192.168.XXX.XXX:8888/menu.htmlと直接打ち込めば画面表示される。
・パスワードのチェックが働いていない（ログインIDのみの認証になっている。以前からこうだったかは不明です。）

設定変更による影響でしょうか？

**Comment by taisukef** [comment]
こちらで確認したところ特に問題はないようです（以前とその他の変更はありません）
サーバー側、または、ブラウザ側で何かエラーメッセージでていないでしょうか？
また、iPadのiOSのバージョン、教えてください

現状、パスワードは通信時にチェックしているのでその挙動で合ってます

**Comment by yuukia11** [comment]
ご指摘ありがとうございます！
再度確認したところ、誤ったパスワードでログインボタンを押した際に、メニュー画面にはたどり着けますが、エントリー受付などの画面が正しく表示されないことがわかりました。正しいパスワードを入力したら正常に機能しました。
iPadの方はおっしゃるとおりでバージョンが古かったようです。最新のOSにアップデートしたら改善されました。

現在触ってテストしていたのですが、予選の点数入力画面が、正常に動きませんでした。症状としてはタイマーが起動せず、チェックボックスを入れても点数が集計されませんでした。戻るボタンも動かないためブラウザの戻るで戻りました。

ログを見ると予選一覧から試合番号(1-2など)をクリックして、score.htmlを開く際にファイルが無い旨のエラーログが吐かれています。エキシビジョンの画面は正常に動作するので、その差を考えると対戦結果データが見つからないのではと思っているのですが、それ以上は追いきれませんでした。すみませんがご教示いただけると幸いです。

【エラーログ】
NotFound: 指定されたファイルが見つかりません。 (os error 2)
    at async Object.readFile (deno:runtime/js/40_read_file.js:25:20)
    at async Object.CSV.fetchOrLoad (https://js.sabae.cc/CSV.js:268:12)
    at async Object.CSV.fetch (https://js.sabae.cc/CSV.js:277:32)
    at async minidb (file:///C:/kanirobocon-system-main/minidb.js:12:17)
    at async file:///C:/kanirobocon-system-main/kanirobo-server.js:29:15
    at async handleAPI (https://code4fukui.github.io/wsutil/handleAPI.js:6:15)
    at async https://code4fukui.github.io/wsutil/wsutil.js:29:14
    at async Server._serve.port.port (https://code4fukui.github.io/wsutil/wsutil.js:22:12)
    at async Server.#respond (https://deno.land/std@0.157.0/http/server.ts:298:18)

**Comment by taisukef** [comment]
ご確認、ありがとうございます！
データクリアせずに初回のスコア画面で記録できないバグがあり、修正しました

https://github.com/fkpc/kanirobocon-system/commit/32bb4215ef4b103aa5a21f1cbebcae981144328c

**Comment by yuukia11** [comment]
こちらでの返事できておりませんでした。
ご対応ありがとうございました！
予選登録まで無事動作することを確認できました。

歩行型がない大会では決勝トーナメント表作成ができなかったですが
これはこちら独自の問題なので、歩行型のダミーデータを入れるなどして
運用回避でなんとか対処したいと思います！

お忙しい中ご対応いただき、心から感謝しております！

**Comment by taisukef** [comment]
ご確認ありがとうございます！

1部門しかない場合の対応、懸案として Issue には挙げておきます
https://github.com/fkpc/kanirobocon-system/issues/6

他にも、いろいろと気になった部分、記述ください
